---
title: "Bike_sales_dashboard"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
resource_files:
- bikes_tbl.rds
- bikeshops_tbl.rds
- orderlines_tbl.rds
- gadm36_DEU_1_sp.rds
---

```{r setup, include=FALSE}
# Shiny
library(flexdashboard)
library(shiny)
library(shinyWidgets)
library(DT)

# Core
library(tidyverse)
library(lubridate)
library(raster)
library(sf)
library(plotly)
```


```{r}
# Make data
# Bike data
#source("plot_sales.R")
format_to_euro <-
function(x, suffix = " €") {
  
  scales::dollar(x,
                 suffix       = suffix,
                 prefix       = "",
                 big.mark     = ".",
                 decimal.mark = ",")
}
euro_format <-
function(scale        = 1,
                        prefix       = "",
                        suffix       = " €",
                        big.mark     = ".",
                        decimal.mark = ",") {
  
  scales::dollar_format(suffix       = suffix,
                        prefix       = prefix,
                        big.mark     = big.mark,
                        decimal.mark = decimal.mark,
                        scale        = scale)
  
}

bikes_tbl      <- readRDS("bikes_tbl.rds")
bikeshops_tbl  <- readRDS("bikeshops_tbl.rds")
orderlines_tbl <- readRDS("orderlines_tbl.rds")

bike_orderlines_tbl <- orderlines_tbl %>%
    left_join(bikes_tbl,     by = c("product_id" = "bike_id")) %>%
    left_join(bikeshops_tbl, by = c("customer_id" = "bikeshop_id")) %>%
    mutate(total_price = price_euro * quantity)

# German spatial data
germany_sp <- getData('GADM', country='DE', level=1) 
germany_sf <- st_as_sf(germany_sp) %>% 
  
                  # Add english names
                  mutate(VARNAME_1 = ifelse(is.na(VARNAME_1), NAME_1, VARNAME_1)) 

#Input choices

bike_family <- unique(bike_orderlines_tbl$category_2)




```

Sidebar {.sidebar}
------------------------

```{r}
# Inputs
dateRangeInput(inputId = "date_range", 
               label   = h4("Date Range"), 
               start   = "2015-01-7", 
               end     = today(),          # "2019-05-10" 
               min     = min(bike_orderlines_tbl$date), 
               max     = max(bike_orderlines_tbl$date), 
               startview = "year")

prettyCheckboxGroup( # or prettyRadioButtons
  inputId = "bike_type",
  label = "Bike Type:",
  choices = c("Mountain","Road","Hybrid / City","E-Bikes","Gravel"),
  outline = TRUE,
  plain = TRUE,
  status = "primary",
  icon = icon("check")
)

prettyCheckboxGroup( # or prettyRadioButtons
  inputId = "period",
  label = "Period:",
  choices = c("day","week","month","quarter","year"),
  outline = TRUE,
  plain = TRUE,
  status = "primary",
  icon = icon("check")
)

pickerInput(
  inputId = "bike_family", 
  label = "Bike Family:", 
  choices = bike_family, 
  options = pickerOptions(
    actionsBox = TRUE, 
    size = 10,
    selectedTextFormat = "count > 3"
  ), 
  multiple = TRUE
)
```


Column {data-width=500}
---------------------------------------------------------------

### By State

```{r}
  # Reactive Filter
  bike_orderlines_tbl_filtered <- reactive({
    bike_orderlines_tbl %>%
      filter(category_1 %in% input$bike_type) %>%
      filter(order_date %>% between(left = ymd(input$date_range[1]), right = ymd(input$date_range[2]))) %>%
      filter(category_2 %in% input$bike_family)
  })

  # Create reactive plot
  output$plot_1 <- renderPlotly({
    geo_plot_tbl <- bike_orderlines_tbl_filtered() %>%
      group_by(state) %>%
      summarise(total_revenue = sum(total_price)) %>%
      ungroup() %>%
      right_join(germany_sf, by = c("state" = "VARNAME_1")) %>%
      mutate(total_revenue = ifelse(is.na(total_revenue), 0, total_revenue)) %>%
      mutate(label_text = str_glue("State: {state}
                                   Revenue: {format_to_euro(total_revenue)}")) %>%
      st_as_sf()
  
    plot_ly(geo_plot_tbl,
            split = ~NAME_1,
            color = ~total_revenue,
            colors = "Blues",
            stroke = I("black"),
            hoverinfo = 'text',
            text = ~label_text,
            hoveron = "fills",
            showlegend = FALSE)
  })

```

```{r}
plotlyOutput("plot_1")
```


Column {data-width=500}
-----------------------

```{r}
# Plot function

data_tbl <- reactive({
  bike_orderlines_tbl %>%
    filter(category_1 %in% input$bike_type) %>%
    filter(order_date %>% between(left = ymd(input$date_range[1]), right = ymd(input$date_range[2]))) %>%
    filter(category_2 %in% input$bike_family) %>%
    select(order_date, total_price) %>%
    mutate(date_rounded = floor_date(order_date, unit = input$period)) %>%
    group_by(date_rounded) %>%
    summarise(total_sales = sum(total_price)) %>%
    ungroup() %>%
    mutate(label_text = str_glue("Sales: {format_to_euro(total_sales)}
                                  Date: {format(date_rounded, '%Y-%m-%d')}"))
})

    # Make Plot
output$plot_2 <- renderPlotly({
  g1 <- data_tbl() %>%
    ggplot(aes(x = date_rounded, y = total_sales)) +
  
    # Geoms
    geom_point(aes(text = label_text), color = "#2C3E50") +
    geom_smooth(method = "loess", span = 0.2) +
  
    # Formatting
    scale_y_continuous(labels = euro_format()) +
    expand_limits(y = 0) +
    labs(
      title = "Total Sales",
      y = "Revenue (Euro)",
      x = ""
    )
  
  # # Static vs Interactive Logic
  # if (interactive) {
  #   return(ggplotly(g1, tooltip = "text"))
  # } else {
  #   return(g1)
  # }
  
})
```


```{r}
plotlyOutput("plot_2")
```